sonar.projectKey=pritxsh_Easyway
sonar.organization=pritxsh
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.language=java

# Java Binary Configuration
sonar.java.binaries=target/classes

# Exclusions
sonar.exclusions=src/test/**,target/**