spring.application.name=EasywayEmployee


# Hibernate
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
# spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://dpg-d5j9bj56ubrc73ejclf0-a.frankfurt-postgres.render.com:5432/employeedb_ig3j?sslmode=require
spring.datasource.username=employeedb_ig3j_user
spring.datasource.password=Voj10reS2nnn56jIDBsjkwG4yQ7t3YnP
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect




# JWT Configuration
jwt.secret=${JWT_SECRET:your-secret-key-change-this-in-production}
jwt.expiration=${JWT_EXPIRATION:86400000}






